---
- name: Check variables for logical errors
  ansible.builtin.include_tasks:
    file: vars.yml

- name: Set & check infos about the underlying platform (os & packages)
  ansible.builtin.include_tasks:
    file: platform.yml

- name: Set & check infos about paperless-ngx release
  ansible.builtin.include_tasks:
    file: pngx_release.yml
...
