---
- name: install dev dependencies
  ansible.builtin.apt:
    pkg:
      - git
      - npm
      - gettext

- name: create output directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ paperlessng_system_user }}"
    group: "{{ paperlessng_system_group }}"
    mode: "750"
  with_items:
    - "{{ tempdir.path }}/paperless-ngx"
    - "{{ tempdir.path }}/paperless-ngx/scripts"

- name: Prep the deployment
  block:
    - name: create temporary git directory
      ansible.builtin.tempfile:
        state: directory
        path: "{{ paperlessng_directory }}"
      register: gitdir

    - name: pull paperless-ngx
      ansible.builtin.git:
        repo: https://github.com/paperless-ngx/paperless-ngx.git
        dest: "{{ gitdir.path }}"
        version: "{{ paperlessng_version }}"
        refspec: +refs/pull/*:refs/pull/*

    - name: compile frontend
      ansible.builtin.command:
        cmd: "{{ item }}"
      args:
        chdir: "{{ gitdir.path }}/src-ui"
      failed_when: false
      with_items:
        - npm install -g @angular/cli
        - npm install
        - ./node_modules/.bin/ng build --prod

    - name: copy application into place
      ansible.builtin.copy:
        src: "{{ gitdir.path }}/{{ item.src }}"
        remote_src: true
        dest: "{{ tempdir.path }}/paperless-ngx/{{ item.dest | default('') }}"
      with_items:
        - src: CONTRIBUTING.md
        - src: LICENSE
        - src: Pipfile
        - src: Pipfile.lock
        - src: README.md
        - src: requirements.txt
        - src: gunicorn.conf.py
        - src: paperless.conf.example
          dest: paperless.conf

    - name: glob all scripts
      ansible.builtin.find:
        paths: ["{{ gitdir.path }}/scripts/"]
        patterns:
          - "*.service"
          - "*.sh"
      register: glob

    - name: copy scripts
      ansible.builtin.copy:
        src: "{{ item.path }}"
        remote_src: true
        dest: "{{ tempdir.path }}/paperless-ngx/scripts/"
      with_items:
        - "{{ glob.files }}"

    - name: copy sources
      ansible.builtin.command:
        cmd: cp -r src/ {{ tempdir.path }}/paperless-ngx/src
      args:
        chdir: "{{ gitdir.path }}"

    - name: create paperlessng venv
      ansible.builtin.command:
        cmd: python3 -m virtualenv {{ gitdir.path }}/.venv/ -p /usr/bin/python3

    - name: install paperlessng requirements
      ansible.builtin.command:
        cmd: "{{ gitdir.path }}/.venv/bin/python3 -m pip install -r {{ gitdir.path }}/requirements.txt"

    - name: compile messages
      ansible.builtin.command: "{{ gitdir.path }}/.venv/bin/python3 manage.py compilemessages"
      args:
        chdir: "{{ tempdir.path }}/paperless-ngx/src/"

    - name: collect static files
      ansible.builtin.command: "{{ gitdir.path }}/.venv/bin/python3 manage.py collectstatic --no-input"
      args:
        chdir: "{{ tempdir.path }}/paperless-ngx/src/"

    - name: remove pycache directories
      ansible.builtin.shell: find . -name __pycache__ | xargs rm -r
      args:
        chdir: "{{ tempdir.path }}"

    - name: remove temporary git directory
      ansible.builtin.file:
        path: "{{ gitdir.path }}"
        state: absent

  become: true
  become_user: "{{ paperlessng_system_user }}"
