---
- name: Create paperless system group
  become: true
  ansible.builtin.group:
    name: "{{ paperless_ngx_system_group }}"
    gid: "{{ paperless_ngx_conf_usermap_gid | default(omit) }}"

- name: Create paperless system user
  become: true
  ansible.builtin.user:
    name: "{{ paperless_ngx_system_user }}"
    uid: "{{ paperless_ngx_conf_usermap_uid | default(omit) }}"
    group: "{{ paperless_ngx_system_group }}"
    groups: "{{ paperless_ngx_system_user_additional_groups }}"
    append: true
    shell: /usr/sbin/nologin
    create_home: true
    comment: Paperless-ngx system user
...
