---
name: Code Testing

"on":
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*version.txt"
      - "maintenance/**"
      - "docs/**"
      - ".github/**"
      - "!.github/**/*test*.yml"
      - "!.github/**/*constraints*.txt"
      - "!.github/**/*requirements*.txt"
      - "!.github/**/*env*.txt"
      # - "!.github/**/*release*.yml"
  schedule:
    - cron: "0 7 * * 5"  # At 07:00 on Friday

jobs:
  molecule_test:
    strategy:
      matrix:
        distro:
          - debian11
          - debian12
          - debian13
          # https://github.com/geerlingguy/docker-ubuntu2204-ansible/issues/6
          - ubuntu2204
          - ubuntu2404
          # - ubuntu2004
        molecule_scenario: [
          alternative_installation,
          check_fails,
          default,
          postgresql_db,
          reconfigure,
          upgrade
        ]
        include:
          - molecule_scenario: default
            ansible_version_minimum: "2.15"
            ansible_package_version_minimum: "8.0.0"

    name: Molecule Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Load environment vars
        id: dotenv
        uses: falti/dotenv-action@v1.1.5
        with:
          path: .github/workflows/env_vars.txt
          log-variables: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ steps.dotenv.outputs.PYTHON_SETUP_VERSION }}

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip
          python3 -m pip --version

      - name: Install test dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          retry_wait_seconds: 20
          max_attempts: 3
          command: |
            if [ -z "${{ matrix.ansible_version_minimum }}" ]
            then
              python3 -m pip install -r .github/workflows/requirements.txt -c .github/workflows/constraints.txt
            else
              python3 -m pip install ansible-core==${{ matrix.ansible_version_minimum }}.* ansible==${{ matrix.ansible_package_version_minimum }} \
              -r .github/workflows/requirements.txt
            fi

            molecule --version
            docker --version
            ansible-galaxy install --verbose -r requirements.yml
            ansible-galaxy collection list

      - name: Run Molecule tests
        run: molecule test --scenario-name ${{ matrix.molecule_scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          TEST_MOLECULE_LINT: false
          TEST_MOLECULE_DISTRO: ${{ matrix.distro }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
